# SPDX-FileCopyrightText: 2019 Free Software Foundation Europe e.V.
#
# SPDX-License-Identifier: GPL-3.0-or-later

pipeline:
  deploy:
    image: tmaier/docker-compose
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker-compose build
      - docker-compose up -d
    when:
       event:
         - push
         - tag
         - deployment
       branch: master
