---
# SPDX-FileCopyrightText: Free Software Foundation Europe e.V.
#
# SPDX-License-Identifier: GPL-3.0-or-later
kind: pipeline
name: default

steps:
  # Check for REUSE compliance
  - name: reuse
    image: fsfe/reuse:latest
    commands:
      - reuse lint

  - name: quality-image
    image: docker:20
    environment:
      # Docker configuration
      XDG_RUNTIME_DIR: "/run/user/1001"
      DOCKER_HOST: "unix:///run/user/1001/docker.sock"
    volumes:
      - name: dockersock
        path: /run/user/1001/docker.sock
    commands:
      - docker compose -p reuse-api --file docker-compose.quality.yml build

  # Run pytest
  - name: quality
    image: reuse-api-quality
    pull: never
    commands:
      - isort --check --diff reuse_api tests/* *.py
      - black --check --diff reuse_api tests/* *.py
      - pylama reuse_api tests/* *.py
      - pytest tests
    depends_on:
      - quality-image

  # Build and deploy Docker
  - name: deploy
    image: docker:20
    commands:
      - docker compose -p reuse-api up --build -d
    environment:
      XDG_RUNTIME_DIR: "/run/user/1001"
      DOCKER_HOST: "unix:///run/user/1001/docker.sock"
      SECRET_KEY:
        from_secret: secret_key
    volumes:
      - name: dockersock
        path: /run/user/1001/docker.sock
    depends_on:
      - quality
    when:
      branch:
        - master
      event:
        - push
        - tag
        - deployment

node:
  cont2: noris

volumes:
  - name: dockersock
    host:
      path: /run/user/1001/docker.sock
---
kind: signature
hmac: ac904f97657e956463a275ae8dca5c431f7e452eb761f4ebd1aab626a742bd12

...
