---
# SPDX-FileCopyrightText: Free Software Foundation Europe e.V.
#
# SPDX-License-Identifier: GPL-3.0-or-later
kind: pipeline
name: default

steps:
  # Check for REUSE compliance
  - name: reuse
    image: fsfe/reuse:latest
    commands:
      - reuse lint

  # Build and deploy Docker
  - name: deploy
    image: docker/compose:1.29.2
    commands:
    - docker-compose -p reuse-api up --build -d
    environment:
      SECRET_KEY:
        from_secret: secret_key
    volumes:
    - name: dockersock
      path: /var/run/docker.sock
    when:
      branch:
      - master
      event:
      - push
      - tag
      - deployment

node:
  cont: lund

volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock

...
