---
# SPDX-FileCopyrightText: Free Software Foundation Europe e.V.
#
# SPDX-License-Identifier: GPL-3.0-or-later
kind: pipeline
name: default

steps:
  # Check for REUSE compliance
  - name: reuse
    image: fsfe/reuse:latest
    commands:
      - reuse lint

  # Build and deploy Docker
  - name: deploy
    image: docker/compose:1.29.2
    commands:
      - docker-compose -p reuse-api up --build -d
    environment:
      XDG_RUNTIME_DIR: "/run/user/1001"
      DOCKER_HOST: "unix:///run/user/1001/docker.sock"
      SECRET_KEY:
        from_secret: secret_key
    volumes:
      - name: dockersock
        path: /run/user/1001/docker.sock
    when:
      branch:
        - master
      event:
        - push
        - tag
        - deployment

node:
  cont2: noris

volumes:
  - name: dockersock
    host:
      path: /run/user/1001/docker.sock
---
kind: signature
hmac: 33c984a08bc0331bdf2c29e5f5814a99f7550b1e52ef82cd0dbe6aa6023ae218

...
