#!/bin/sh
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright © 2019 Free Software Foundation Europe e.V.

REPO=$1
ENV=$2
TMP=$(mktemp)

if [ -z ${REPO} ]; then
  echo "No repo URL provided"
  exit 41
fi

if [ -z ${ENV} ]; then
  docker run --rm reuse-api "${REPO}"
  status=$?
else
  echo "REUSE_OPT=$ENV" > $TMP
  cat $TMP
  docker run --env-file $TMP --rm reuse-api "${REPO}"
  status=$?
fi

rm $TMP

exit $status
